### ISSUE TITLE
Join Study Room - Button is not working 

### ISSUE THREAD

**Issue by tier3guy** [tier3guy/Acadmica#10]
Update the link in the join button.

**Comment by tier3guy** [comment]
Hey, @Parzivalcen
Here is the link : https://tier3guy.github.io/Acadmica/public/studyroom.html

Go for it.

**Comment by Roshani9731** [comment]
@tier3guy Can I work on this issue?

**Comment by tier3guy** [comment]
Go for it @Roshani9731

**Comment by rakshitgondwal** [comment]
Study room button seems working perfectly for me though.
