### ISSUE TITLE
Too much padding and overlapping text in small breakpoints.

### ISSUE THREAD

**Issue by jklagrosa** [tier3guy/Acadmica#106]
#### Always double-check that the changes are also applicable to small devices/breakpoints.

#

![image](https://user-images.githubusercontent.com/104843990/183411361-7839f8ef-bc22-4ff9-8ac3-935ef34792a3.png)

![image](https://user-images.githubusercontent.com/104843990/183411180-9e95b6be-79b3-4a8d-aaef-3bc2a7571248.png)

**Comment by fykaa** [comment]
Hi, I want to work on this, assign this to me. 
I will work towards making this section responsive, as I see the content doesn't flows freely across all screen resolutions and sizes and renders it to not look great on all devices.
@tier3guy 
Name: Fyka 
SSOC'22 Participant

**Comment by fykaa** [comment]
Hey, @jklagrosa Would you please tell us about the dimensions of your device, so it gets easier to recheck on that resolution?

**Comment by jklagrosa** [comment]
> Hey, @jklagrosa Would you please tell us about the dimensions of your device, so it gets easier to recheck on that resolution?

It is the standard browser dimension for small devices, which is 320 x 570.

**Comment by tier3guy** [comment]
Issue is fixed on the latest merges.
