### ISSUE TITLE
Multiple MISSPELLINGS on the main content

### ISSUE THREAD

**Issue by fykaa** [tier3guy/Acadmica#108]
Issue - When I checked the website, I discovered that there were numerous misspellings throughout the content, as well as grammatical and daft errors. I'm eager to address all of them because the content is such an important part of a website's SEO, which can detract readers and customers while also creating backlash for inaccurate writings!

@tier3guy  Please assign me this issue since I'm looking forward to work asap
SSOC'22 Participant

**Comment by fykaa** [comment]
![Screenshot (685)](https://user-images.githubusercontent.com/97490463/183482142-92d513b8-c195-4605-9544-4ab9e4250e99.png)

For example

**Comment by tier3guy** [comment]
Good Job @fykaa. Go for it.

**Comment by narayan954** [comment]
marking this as completed in pr #131
