### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by tier3guy** [tier3guy/Acadmica#11]
Update and redesign the current readme and build a fresh one as there were lots of changes from day 1 on the site. 

The readme will contain - 

> The Organization name
> Mission
> How to contribute to it
> Folder structuture 
> contributors

**Comment by Arpit-mohankar** [comment]
can i contributr to this issue

**Comment by tier3guy** [comment]
@Arpit-mohankar Go for it. I am assigning it you !!

**Comment by tier3guy** [comment]
@Arpit-mohankar What is the update ?

**Comment by Arpit-mohankar** [comment]
@tier3guy hey i have done that two days ago itself but i think i pull my request on some other repository sorry
i am newbie here

**Comment by Arpit-mohankar** [comment]
@tier3guy Hey i have made pull request please review and merge!!
