### ISSUE TITLE
Faq +/- toggle button is disturbed

### ISSUE THREAD

**Issue by tushar-glitch** [tier3guy/Acadmica#120]
![Screenshot (234)](https://user-images.githubusercontent.com/67220766/184067372-c695d900-9397-48ef-acc8-41a9678a4e4b.png)
Suppose we click on a question then the + to - effect is working on the next question. Please assign me this issue. I can fix it.

**Comment by SushanthReddy-49** [comment]
I believe that is expected... When you open one question all questions are collapsed.. what say @tier3guy

**Comment by tushar-glitch** [comment]
No, but the question that is currently opened should show the option of '-'.

**Comment by tier3guy** [comment]
> ![Screenshot (234)](https://user-images.githubusercontent.com/67220766/184067372-c695d900-9397-48ef-acc8-41a9678a4e4b.png)
> Suppose we click on a question then the + to - effect is working on the next question. Please assign me this issue. I can fix it.

Valid !!!
