### ISSUE TITLE
Theme changer not working

### ISSUE THREAD

**Issue by AnshuPathak-88825** [tier3guy/Acadmica#122]

**Comment by AnshuPathak-88825** [comment]
pls assign me this is issue

**Comment by SushanthReddy-49** [comment]
@AnshuPathak-88825 can you mention in which device it is not working?
It is working fine in my device.

**Comment by AnshuPathak-88825** [comment]
in my laptop

**Comment by vaibhavsharma1234** [comment]
Mee too 
I created it

**Comment by SushanthReddy-49** [comment]
Sorry Guys @vaibhavsharma1234 @AnshuPathak-88825  it is working on my Mobile, but not on the Production website. In my local, it is actually working well.
@tier3guy can you take a look into this.

**Comment by vaibhavsharma1234** [comment]
Someone may have messed the code otherwise there should be no problem

**Comment by vaibhavsharma1234** [comment]
@SushanthReddy-49 bro did u change something if yes
then u can msg me on discord i can help you as i implemented the theme changer

**Comment by vaibhavsharma1234** [comment]
https://github.com/tier3guy/Acadmica/issues/119
@AnshuPathak-88825  brother is it ok if i fix this issue as i am doing other issue related to the theme switcher 
it will be convient otherwise there may occur issues

**Comment by vaibhavsharma1234** [comment]
i have fixed it the problem was that ur js was not working properly 
there was no need to change it

**Comment by vaibhavsharma1234** [comment]
https://github.com/tier3guy/Acadmica/issues/122

**Comment by SushanthReddy-49** [comment]
> @SushanthReddy-49 bro did u change something if yes then u can msg me on discord i can help you as i implemented the theme changer

Hi, Yes I did some changes in the code, by adding icon change code. It is working as expected in my Local.
Share the discord ID. We can connect and talk if anything is necessary.

**Comment by vaibhavsharma1234** [comment]
i have solved it 
Vaibhav Sharma#2589

**Comment by narayan954** [comment]
This issue is already in progress . Please refrain from creating duplicate issues and follow up on original issues only.
