### ISSUE TITLE
Website's background color

### ISSUE THREAD

**Issue by ArunaAT** [tier3guy/Acadmica#130]
I would like to change the background colour of the  main page, which is grey at the moment, I can add colour gradient to it.

**Comment by narayan954** [comment]
go ahead @ArunaAT and please provide your work's screenshots along with the PR. Thank you :)

**Comment by ArunaAT** [comment]
I will start working on it right away, after completing I will send you a
Screenshot with PR.

**Comment by prjailani** [comment]
Hi if she is not working on that can you re-open my PR and merge it @narayan954 ?

**Comment by narayan954** [comment]
solve on #159
