### ISSUE TITLE
Add content to electrical, mechanical, civil and electronics pages

### ISSUE THREAD

**Issue by narayan954** [tier3guy/Acadmica#134]
Electrical, mechanical, civil and electronics pages are missing content , try to add it

**Comment by fykaa** [comment]
@narayan954  What kind of Content is supposed to be added, Please elaborate, I would want to work on this issue

**Comment by fykaa** [comment]
@myhacktech Please merge PR 163 with this issue

**Comment by narayan954** [comment]
Thanks for the contribution. Closing this as a completed issue.
