### ISSUE TITLE
Add Setup guidelines and Contribution guidelines in the readme file

### ISSUE THREAD

**Issue by VaibhavSinghDev** [tier3guy/Acadmica#135]
Readme file should consist of the steps to clone and set up the repository and set up the project for beginners to start contributing.

**Comment by narayan954** [comment]
Great idea!, you can work on this. :)

**Comment by VaibhavSinghDev** [comment]
Thanks! I will start working on it

**Comment by narayan954** [comment]
sorry @VaibhavSinghDev but I can't confirm this as completed. Can you please mention the pr raised for this issue?

**Comment by VaibhavSinghDev** [comment]
Did you get the PR already? @narayan954

**Comment by narayan954** [comment]
yes I did , thank you for your contribution!
