### ISSUE TITLE
Need A fix for Color Coordination and Transient Effects to some buttons

### ISSUE THREAD

**Issue by fykaa** [tier3guy/Acadmica#137]
I'd like to fix and improve the colour design and hovering features on several buttons of the main page.

The text ain't visible in the below hovering feature
![Screenshot (710)](https://user-images.githubusercontent.com/97490463/184981774-f5350ac7-3a54-41a0-b7f5-b39ee90b4b78.png)
Improving this -
![Screenshot (711)](https://user-images.githubusercontent.com/97490463/184981838-e04f2c26-5629-44ab-90b8-bf22441d47c3.png)
Choosing better gradients for this-
![Screenshot (712)](https://user-images.githubusercontent.com/97490463/184981806-b8bca534-1382-42ee-bc18-8f75979c2f14.png)

**Comment by fykaa** [comment]
Assign me this . SSOC Participant

**Comment by narayan954** [comment]
closing this as completed!
