### ISSUE TITLE
Modifying the font-colors 

### ISSUE THREAD

**Issue by ganesh-utla** [tier3guy/Acadmica#144]
Need a fix to font-color, as it isn't visible enough to read in dark theme!!
![image](https://user-images.githubusercontent.com/87692393/187026898-3b55d2dc-8951-4871-b0ae-c0d5179964f1.png)
![image](https://user-images.githubusercontent.com/87692393/187028709-e8955a07-6579-4345-8e3d-d767a7dea317.png)
![image](https://user-images.githubusercontent.com/87692393/187028751-69d11a9e-0321-47d4-a7c7-896490840b2e.png)
@myhacktech / @narayan954 / @tier3guy Can you assign it to me?

**Comment by narayan954** [comment]
Go on!! :)

**Comment by narayan954** [comment]
marking this as completed with #153
