### ISSUE TITLE
To Update Ui(images and its background)

### ISSUE THREAD

**Issue by Kirankp25** [tier3guy/Acadmica#151]
I would like to add one image which will really correlate with the topic which you are delivering to students it will help them to catch the concept easily by this image and also want to change some UI  related changes
![Screenshot (221)](https://user-images.githubusercontent.com/87818185/187447941-2d70aa4c-9abf-44f6-bbdc-0293591284f7.png)

**Comment by kirtanchandak** [comment]
Can you assign this to me ?
