### ISSUE TITLE
Build a Custom 4O4 Error page

### ISSUE THREAD

**Issue by tier3guy** [tier3guy/Acadmica#16]
Build a custom-beautiful 4O4 page for the site. Maintaining the theme.

Add on's : 
Try be unique will designing the page.

**Comment by losier** [comment]
I can try to make you a custom 404 page.
what are your requirements on that page.

**Comment by tier3guy** [comment]
Nothing much, just a 404 big text, with a sweet message below it.
Also, the page will contain a button [ go back to home ] something like this, that will redirect the user to the home page.

**Comment by tier3guy** [comment]
If you are comfortable tell me, and I will assign it to you !!

**Comment by losier** [comment]
Sure @tier3guy i'll submit my code by tomorrow afternoon. One more thing can you tell me the background like you want a light background or a dark background

**Comment by tier3guy** [comment]
You can start with the light theme.

**Comment by losier** [comment]
Hey @tier3guy here is my pr #24 for this issue

**Comment by tier3guy** [comment]
@losier the back button in your page is not working. 

Also the page is too fancy. You must design a minimal page. always try to maintain the theme of the org. ( use blue & white colors ) 

I have merged your previous pull request.
If you want to work on the changes you can let me know, otherwise we raise one other issues for the enhancement in 4O4 page.

**Comment by losier** [comment]
Ok give me some time ill try to make one more 404 page soon

**Comment by losier** [comment]
@tier3guy should i share the screenshot first tims time?>

**Comment by tier3guy** [comment]
> @tier3guy should i share the screenshot first tims time?>

No not required now

**Comment by losier** [comment]
Hope you like this one this time it's based on your website theme and tried to make it minimal.
[Image}(https://ibb.co/tpL0GZJ)

**Comment by tier3guy** [comment]
@losier The image is not visible to me. Just drag and drop the SS of the changes into the comment box here.

**Comment by losier** [comment]
![Screenshot 2022-07-18 111825](https://user-images.githubusercontent.com/85448514/179455992-c6677166-c5ca-429f-8fe3-39063810de49.png)
