### ISSUE TITLE
Adding Dark mode in Studyroom page

### ISSUE THREAD

**Issue by ganesh-utla** [tier3guy/Acadmica#167]
I would like to add the dark mode facility to the studyroom  page and also solving some navbar font-color issues in the dark mode of Academics and Development pages, which is unclear to read!
![image](https://user-images.githubusercontent.com/87692393/190844653-4fae14ef-e4db-46f1-a3f7-bda031c80d2f.png)
Can you assign it to me?

**Comment by narayan954** [comment]
great go ahead!
