### ISSUE TITLE
Update the discord button link in each page 

### ISSUE THREAD

**Issue by tier3guy** [tier3guy/Acadmica#18]
The updated link ~ https://discord.gg/ZkHXnxhda7

**Comment by Trevy05** [comment]
Can I have this issue?

**Comment by tier3guy** [comment]
Go for it.

**Comment by con-artist** [comment]
can you assign me this issue please under ssoc

**Comment by tier3guy** [comment]
This issue is already been assigned. @con-artist You can look at some other issues. We are waiting for your contribution.

**Comment by narayan954** [comment]
Issue was resolved , so closing this.
