### ISSUE TITLE
Update the page link in development section

### ISSUE THREAD

**Issue by tier3guy** [tier3guy/Acadmica#19]
In the page ~ https://acadmica.social/src/pages/development/main.html

![Screenshot 2022-07-17 at 18-22-46 Acadmica](https://user-images.githubusercontent.com/73595465/179399242-4721ad67-72cf-44ca-980f-ed16bfa4b82e.png)

In the above section the links are not working while pages are created already. Do attach the links of the pages.

**Comment by Korra15** [comment]
Could you please assign this to me under SSOC 2022

**Comment by tier3guy** [comment]
Yeah sure @Korra15
