### ISSUE TITLE
In the navbar add one more link to the github repo

### ISSUE THREAD

**Issue by tier3guy** [tier3guy/Acadmica#20]
![Screenshot 2022-07-17 at 18-40-21 Acadmica](https://user-images.githubusercontent.com/73595465/179399933-95962a9c-27ca-49b9-acb9-f4ad9aa7d10c.png)

Before the Subscribe US button, add the github icon put the link to the repo

**Comment by nalin-singh** [comment]
Before contributing any format to follow ?

**Comment by Jasleen-001** [comment]
> ![Screenshot 2022-07-17 at 18-40-21 Acadmica](https://user-images.githubusercontent.com/73595465/179399933-95962a9c-27ca-49b9-acb9-f4ad9aa7d10c.png)
> 
> Before the Subscribe US button, add the github icon put the link to the repo

Please assign this issue to me

**Comment by tier3guy** [comment]
@nalin-singh The only format is to maintain the theme and to follow the project code structure.
Add on's : Try to write responsive code that can also work for other media devices also.

**Comment by tier3guy** [comment]
So, @nalin-singh @Jasleen-001 I am assigning it to both of you for now. try to collab with each other or you guys divide the tasks, or you guys can talk to each other.

**Comment by tier3guy** [comment]
@Jasleen-001 @nalin-singh What is the status ?

**Comment by Jasleen-001** [comment]
![image](https://user-images.githubusercontent.com/89333454/180226173-43d376cb-8559-4235-a7e3-e107be075bab.png)
Is this right ? I can add the icon of github instead of "Github Repository" as well but it would look odd plus this method also aligns with all the other important links so I made it this way.Let me know if any you want it other way around.

**Comment by tier3guy** [comment]
Okay it's okay. But if you are writing it on text just write "GitHub" instead of "GitHub repository"

**Comment by narayan954** [comment]
Closing this as completed.
