### ISSUE TITLE
Dark Implementation 

### ISSUE THREAD

**Issue by tier3guy** [tier3guy/Acadmica#22]
Implement a dark and a toggle button to switch between light mode and dark mode.

Theme : 
Dark BG : # 3D3C42
Blue : # 1363DF
Light blue : # 7FB5FF
white : # ffffff

**Comment by Korra15** [comment]
Could you please assign this to me under SSOC 2022

**Comment by Korra15** [comment]
which page does this need feature to be implemented?

**Comment by tier3guy** [comment]
For now start with home page !! We want it on the whole org.

**Comment by vaibhavsharma1234** [comment]
if possible assign it to me if other person is not able to do

**Comment by narayan954** [comment]
@vaibhavsharma1234 are you still available to be assigned?

**Comment by vaibhavsharma1234** [comment]
Ya ofcourse why not

**Comment by narayan954** [comment]
go for it!

**Comment by vaibhavsharma1234** [comment]
update - i have implemented the theme switcher on main page for now 
one issue i am facing is that its working on desktop screen and not in mobile and tablet 
that i am trying to figure out

**Comment by tier3guy** [comment]
Share SS

**Comment by vaibhavsharma1234** [comment]
https://github.com/tier3guy/Acadmica/pull/107
Ss is here 
The issue of Mobile is resolved

**Comment by vaibhavsharma1234** [comment]
This is completed

**Comment by narayan954** [comment]
Thanks for the reminder :) @vaibhavsharma1234
