### ISSUE TITLE
Donate button at the footer

### ISSUE THREAD

**Issue by tier3guy** [tier3guy/Acadmica#23]
@ https://acadmica.social 
@ the footer of the site, a donate button / buy me a coffee button is added 

The button is only available on the index page / home page, make it available on all the other pages 
Also the button is not responsive for media devices <= 700px, make it responsive

**Comment by ivanetra** [comment]
Hi @tier3guy, could u assign the issue to me?

**Comment by tier3guy** [comment]
@ivanetra Go for it.

**Comment by ivanetra** [comment]
Thank you @tier3guy !
