### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by 2024-SANDHYA** [tier3guy/Acadmica#40]
Adding favicon on each and every connected webpages

**Comment by Aman-Singh-Kushwaha** [comment]
Hey, I can do it

**Comment by tier3guy** [comment]
Go for it

**Comment by 2024-SANDHYA** [comment]
@tier3guy I opened the issue and according to the rules, the issue should be assigned to me and not any other person commenting on the issue.

**Comment by tier3guy** [comment]
@2024-SANDHYA Raising one issue and asking for assignment are two different things,
You raised one issue that's good, that is also one contribution but if you want work on that issue you should ask for assigning that issue. 
Hope you got my point. By the way if you want to work on this you can go ahead with this, I will merge both PR's and if some changes will be required, I will assign it back to you.
But for the future references, always for assignment.

**Comment by Aman-Singh-Kushwaha** [comment]
@tier3guy  Hey, 
Please review favicon work
<img width="184" alt="image" src="https://user-images.githubusercontent.com/96011814/180667236-3afa1345-5025-4959-abdc-6437ca78d405.png">

**Comment by Aman-Singh-Kushwaha** [comment]
this favicon also matches the colour palette and the navbar logo

**Comment by Aman-Singh-Kushwaha** [comment]
@tier3guy please add SSoC2022 tag on this issue too, so that it can be considered

**Comment by Aman-Singh-Kushwaha** [comment]
Hey @tier3guy, I have **completed** it and raised  PR #87  please check it out and review it

**Comment by narayan954** [comment]
closing this issue as it has been resolved by @Aman-Singh-Kushwaha
