### ISSUE TITLE
Contrast in button text

### ISSUE THREAD

**Issue by Aspireve** [tier3guy/Acadmica#44]
There is very less contrast on the _**Join Study Room**_ , maybe a more white color or the website theme color can be used to increase the contrast

![image](https://user-images.githubusercontent.com/93852415/180484677-09ea4a9a-cf2b-400e-bcad-6e6047416c8d.png)

**Comment by Aspireve** [comment]
Hey @tier3guy Could I work on this one?

**Comment by tushar-glitch** [comment]
hey there, I want to work on this issue. Could you please assign it to me?
