### ISSUE TITLE
Discord button not working in the Home page.

### ISSUE THREAD

**Issue by tier3guy** [tier3guy/Acadmica#5]
Discord button is not working in the home page. Attach the link of the discord on that.

**Comment by rohangupta8756** [comment]
I would like to take up this.

**Comment by tier3guy** [comment]
Hey @rohangupta8756 the link in the Discord button is still not updated here, please do this so that I can close this issue.
![Join btn](https://user-images.githubusercontent.com/73595465/179149514-22d05daa-093b-45f3-8cce-cd5b13348f9d.jpeg)

**Comment by rohangupta8756** [comment]
@tier3guy  I think there's some issue with the file and i'm unable to figure it out exactly.  After updating the code, it doesn't work. That is why i'm unable to update the link there.

**Comment by tier3guy** [comment]
Have you created any separate branch for it ??

**Comment by rohangupta8756** [comment]
No, I had committed it to my repo which I forked.

**Comment by Roshani9731** [comment]
@tier3guy Can I work on this issue?

**Comment by tier3guy** [comment]
Go for it @Roshani9731

**Comment by rakshitgondwal** [comment]
Discord button seems working perfectly for me though.
