### ISSUE TITLE
1. Show menu at 991px instead of 700px | 2. Add overflow-x: hidden

### ISSUE THREAD

**Issue by jklagrosa** [tier3guy/Acadmica#61]
# BEFORE
![image](https://user-images.githubusercontent.com/104843990/181212094-f1bf428b-cd1e-408c-90ba-498c5e0925e1.png)

- Menu shows at 700px

# AFTER
![image](https://user-images.githubusercontent.com/104843990/181211918-2ed58858-a297-46b7-af72-888711cc2bdd.png)

**Comment by jklagrosa** [comment]
I`m already working on it.

**Comment by tier3guy** [comment]
Great job ||

**Comment by jklagrosa** [comment]
It`s already in pull request.

**Comment by narayan954** [comment]
Marking this as completed now
