### ISSUE TITLE
Fix the footer all the pages - make it to the center

### ISSUE THREAD

**Issue by tier3guy** [tier3guy/Acadmica#66]
![image](https://user-images.githubusercontent.com/73595465/181519849-4cff5a65-8543-4fe2-9dce-c556403c2bfb.png)

The footer is not in the middle

**Comment by SushanthReddy-49** [comment]
By footer do you mean the 2022@cademia Inc ?
I can fix that.
@tier3guy

**Comment by tier3guy** [comment]
The footer is not in the center !!

**Comment by tier3guy** [comment]
URL - https://acadmica.social/src/pages/development/main.html

**Comment by SushanthReddy-49** [comment]
I will fix this. Assign this to me
@tier3guy

**Comment by narayan954** [comment]
Closing this as completed now
