### ISSUE TITLE
Better interface for discord button

### ISSUE THREAD

**Issue by Harsh3363** [tier3guy/Acadmica#72]
Hii 
The button Discord next to join study room will look good if we add some hover effect.

**Comment by Harsh3363** [comment]
@tier3guy please assign this to me 
I have made some changes it would look something like this on hover:

![Screenshot (89)](https://user-images.githubusercontent.com/72756692/182013362-3adcf939-0853-40f0-92e5-b57247b9f842.png)

**Comment by Himanshu-370** [comment]
@tier3guy Hey I did some minor changes too like the **buttons** and **hover effects.**


![1](https://user-images.githubusercontent.com/96609252/182197481-c66927a1-d0d3-4f03-b8b5-f7a389c0df24.png)
![image](https://user-images.githubusercontent.com/96609252/182197568-c2474c96-ac8e-4286-8b9a-3c536d1ccf08.png)

**Comment by tier3guy** [comment]
Hover is good, but keep the button style as of the previous one.

**Comment by Harsh3363** [comment]
> Hover is good, but keep the button style as of the previous one.

Sure 👍

**Comment by narayan954** [comment]
Closing this as completed
