### ISSUE TITLE
Improvement on 'Contact Us' Buttons

### ISSUE THREAD

**Issue by Aman-Singh-Kushwaha** [tier3guy/Acadmica#73]
@tier3guy I can improve UX by improving contact us buttons and adding Some Hover Effect

**Comment by Aman-Singh-Kushwaha** [comment]
Please assign this work to  me
![image](https://user-images.githubusercontent.com/96011814/182378854-bd6c84d1-0caf-470c-b528-25e1773b1b67.png)

**Comment by Aman-Singh-Kushwaha** [comment]
Also the mail id hover color can be changed to match UI

**Comment by myhacktech** [comment]
@Aman-Singh-Kushwaha i am assigning this issue to you,reply if you are still interested

**Comment by Aman-Singh-Kushwaha** [comment]
Hey I have submitted PR #96 
please review my work

**Comment by myhacktech** [comment]
great

**Comment by Aman-Singh-Kushwaha** [comment]
Thanks, Mentors and Project Maintainers

Now we can close this issue
