### ISSUE TITLE
i want to improve responsive ness of the main page

### ISSUE THREAD

**Issue by vaibhavsharma1234** [tier3guy/Acadmica#82]

**Comment by myhacktech** [comment]
@vaibhavsharma1234 describe it along with screenshot and link

**Comment by vaibhavsharma1234** [comment]
![p1](https://user-images.githubusercontent.com/96341386/183009921-67fbad79-8c64-47df-8f5f-cd570d33ca11.png)
resposive ness is good in mobile and pc but its not in tablet mode 
like shown in picture

**Comment by vaibhavsharma1234** [comment]
what level of issue tag is on this ?

**Comment by vaibhavsharma1234** [comment]
this issue is completed close it
