### ISSUE TITLE
To Improve UI(how acadmica works)

### ISSUE THREAD

**Issue by Kirankp25** [tier3guy/Acadmica#84]
I would like to improve the UI of a page (HOW ACADEMICA WORKS)which is attached given below and add frames to given images to be visible clearly. so assign me this issue.

![Screenshot (209)](https://user-images.githubusercontent.com/87818185/182895388-116e4b64-3167-438f-b096-f2f1704dc145.png)

**Comment by myhacktech** [comment]
@Kirankp25 i am assigned this issue to you ,it would be better if you send screenshots of your better version before creating a PULL request.

**Comment by Kirankp25** [comment]
> @Kirankp25 i have assigned this issue to you ,it would be better if you send screenshots of your better version before creating a PULL request.

ya sure

**Comment by Kirankp25** [comment]
These are changes made by me if you have any suggestions put here I will work on it
#84
![Screenshot (219)](https://user-images.githubusercontent.com/87818185/187047049-d38c1691-cefb-4224-9f32-68c428613ae5.png)

**Comment by myhacktech** [comment]
> These are changes made by me if you have any suggestions put here I will work on it #84 ![Screenshot (219)](https://user-images.githubusercontent.com/87818185/187047049-d38c1691-cefb-4224-9f32-68c428613ae5.png)

@tier3guy

**Comment by tier3guy** [comment]
@myhacktech @Kirankp25 I think this is good and we can merge it.

**Comment by Kirankp25** [comment]
ok

**Comment by Kirankp25** [comment]
so pls merge it
https://github.com/tier3guy/Acadmica/pull/145
