### ISSUE TITLE
Improve UI on the home page

### ISSUE THREAD

**Issue by Anjuli08** [tier3guy/Acadmica#85]
The **content** is not very well aligned with the **Image**, So i would like to align it. 
Also **Join Study Room** button styling is not appropriate. So i want to edit it and the **discord button** also!!
![home academica](https://user-images.githubusercontent.com/90701800/182909488-93be97a6-eb6c-48ed-93f8-566d3ed35d4e.png)

**Comment by narayan954** [comment]
@Anjuli08 I am assigning this issue to you ,it would be better if you send screenshots of your better version before creating a PULL request. Happy Contributing.

**Comment by Anjuli08** [comment]
> @Anjuli08 I am assigning this issue to you ,it would be better if you send screenshots of your better version before creating a PULL request. Happy Contributing.

Yeah sure! Thankyou

**Comment by Anjuli08** [comment]
Please review this. I have adjusted the **image** with the leftmost content and tried to improve the styling of **join** study button. it would look more better if the **subscribe button** is also changed like this as well. for the **discord** button I have added this shade as a **hover** effect!

![acad](https://user-images.githubusercontent.com/90701800/183086234-effc8dce-48e4-47ee-b313-6c4dde852ffc.png)


> @Anjuli08 I am assigning this issue to you ,it would be better if you send screenshots of your better version before creating a PULL request. Happy Contributing.

**Comment by tier3guy** [comment]
Good Job, go ahead with the subscribe us button

**Comment by dilpreet102** [comment]
> Please review this. I have adjusted the **image** with the leftmost content and tried to improve the styling of **join** study button. it would look more better if the **subscribe button** is also changed like this as well. for the **discord** button I have added this shade as a **hover** effect!
> 
> ![acad](https://user-images.githubusercontent.com/90701800/183086234-effc8dce-48e4-47ee-b313-6c4dde852ffc.png)
> 
> > @Anjuli08 I am assigning this issue to you ,it would be better if you send screenshots of your better version before creating a PULL request. Happy Contributing.

@Anjuli08 I am designing the buttons below the three sections. So tell me how much value you have given to border radius??

**Comment by dilpreet102** [comment]
2 or 3 px?

**Comment by dilpreet102** [comment]
![image](https://user-images.githubusercontent.com/83696202/183245753-4eabe6a9-ecca-47ac-976d-0d056ab70ffb.png)
@tier3guy now ok?
It would be great if anjuli will add shadow below the buttons as I did...

**Comment by Anjuli08** [comment]
> 2 or 3 px?

5px

**Comment by Anjuli08** [comment]
> ![image](https://user-images.githubusercontent.com/83696202/183245753-4eabe6a9-ecca-47ac-976d-0d056ab70ffb.png) @tier3guy now ok? It would be great if anjuli will add shadow below the buttons as I did...

ok sure! can you tell me values you have added for this??

**Comment by dilpreet102** [comment]
box-shadow: #5e5df0 0 10px 20px -10px;
@Anjuli08

**Comment by dilpreet102** [comment]
> > 2 or 3 px?
> 
> 5px

okkk

**Comment by narayan954** [comment]
Closing this as completed.
