### ISSUE TITLE
Night Mode Effect Switch , CSS Buttons , Text Layout , Faq Section Buttons 

### ISSUE THREAD

**Issue by dilpreet102** [tier3guy/Acadmica#86]
1) I want to change the CSS buttons of all three sections.
2) Text is alligned centre which is not suitable for reading under 'How Acadmica works' section.
3) CSS Buttons layout of FAQ section can be changed.
4) Night Mode Effect Switch can be added on the website.

**Comment by Himanshu-370** [comment]
Assign me this issue

**Comment by tier3guy** [comment]
@Himanshu-370 @dilpreet102,

Dilpreet has raised the issue, so we cannot allocate randomly but if you guys are willing to  collab with each other, that would be great. 

Otherwise we will be assigning it to dilpreet only.

Talk to him if he is willing to collab, then we can assign it to you also.

**Comment by Himanshu-370** [comment]
No problem go ahead @dilpreet102 !!

**Comment by dilpreet102** [comment]
> @Himanshu-370 @dilpreet102,
> 
> Dilpreet has raised the issue, so we cannot allocate randomly but if you guys are willing to collab with each other, that would be great.
> 
> Otherwise we will be assigning it to dilpreet only.
> 
> Talk to him if he is willing to collab, then we can assign it to you also.

Thanks for assigning me the issue. Is there a deadline for submitting the issue?

**Comment by tier3guy** [comment]
> > @Himanshu-370 @dilpreet102,
> > Dilpreet has raised the issue, so we cannot allocate randomly but if you guys are willing to collab with each other, that would be great.
> > Otherwise we will be assigning it to dilpreet only.
> > Talk to him if he is willing to collab, then we can assign it to you also.
> 
> Thanks for assigning me the issue. Is there a deadline for submitting the issue?

Generally we dont give any deadlines but for this particular program we had set a deadline of 3 days. If there will be not contribution found after 3 days from the date of assignment, your assignment will be cancelled and the new candidates will get the issue.

**Comment by dilpreet102** [comment]
> > > @Himanshu-370 @dilpreet102,
> > > Dilpreet has raised the issue, so we cannot allocate randomly but if you guys are willing to collab with each other, that would be great.
> > > Otherwise we will be assigning it to dilpreet only.
> > > Talk to him if he is willing to collab, then we can assign it to you also.
> > 
> > 
> > Thanks for assigning me the issue. Is there a deadline for submitting the issue?
> 
> Generally we dont give any deadlines but for this particular program we had set a deadline of 3 days. If there will be not contribution found after 3 days from the date of assignment, your assignment will be cancelled and the new candidates will get the issue.

Ok thanks.

**Comment by dilpreet102** [comment]
![After Adding Buttons](https://user-images.githubusercontent.com/83696202/183218053-ea97f484-2d0e-4743-968f-ee94ebdc9b38.PNG)
![After adding CSS](https://user-images.githubusercontent.com/83696202/183218058-07872031-504e-4eb2-b0c1-bde98f6bcd7f.PNG)
![Before Adding Buttons](https://user-images.githubusercontent.com/83696202/183218062-7683a325-6efc-47df-a48c-da44ceb8bffc.PNG)
![Interview Section After 2](https://user-images.githubusercontent.com/83696202/183218068-296c3263-1c73-4faa-ac3e-7152b5f2e517.PNG)
![Interview Section After](https://user-images.githubusercontent.com/83696202/183218069-15dd56fb-d6e3-4d10-8635-7f295e3c41e9.PNG)
![Interview Section Before](https://user-images.githubusercontent.com/83696202/183218073-3dc5d302-e067-4c10-aecd-2340bc98e9c9.PNG)
![Normal link](https://user-images.githubusercontent.com/83696202/183218076-1512645e-bbdb-4610-9e88-53558d56d544.PNG)

**Comment by dilpreet102** [comment]
Till Now I have made these changes. Let me know If you are finding these good or not?

**Comment by dilpreet102** [comment]
![image](https://user-images.githubusercontent.com/83696202/183218281-1a1a2e58-bff4-47a2-9af2-e8c18f49090f.png)

**Comment by dilpreet102** [comment]
> ![image](https://user-images.githubusercontent.com/83696202/183218281-1a1a2e58-bff4-47a2-9af2-e8c18f49090f.png)

If you have content for this portion then plese send me .

**Comment by dilpreet102** [comment]
On FAQ and Night Mode effect I am still working .

**Comment by tier3guy** [comment]
@dilpreet102 take reference from #85 for the button design.

**Comment by dilpreet102** [comment]
> No problem go ahead @dilpreet102 !!

if you want to collab then ok. No problem.....

**Comment by dilpreet102** [comment]
![image](https://user-images.githubusercontent.com/83696202/183245889-f27b11de-e2ea-4b19-9521-501c34a56ccf.png)
I have made FAQ section like this, when we hover on that it changes colour and the text also moves.

**Comment by dilpreet102** [comment]
https://user-images.githubusercontent.com/83696202/183246244-b494ad06-cd99-4c30-94a5-cae53169eadb.mp4

I have made these changes in FAQ section.

**Comment by tier3guy** [comment]
Great Work

**Comment by dilpreet102** [comment]
![image](https://user-images.githubusercontent.com/83696202/183258724-a93254ea-9d6c-46a6-bef5-7d927bf513d3.png)
Before

**Comment by dilpreet102** [comment]
![image](https://user-images.githubusercontent.com/83696202/183258739-92f747a7-afc8-4e82-97ef-03098abacc84.png)
After

**Comment by dilpreet102** [comment]
Now only I left with the Night Mode switch , rest I have done my work . Let me know If any changes you want . 
Earlier you were not satisified with the buttons so I have changed according the #85 . 
Also I have changed the color of icons in the Acedemics and Development section which earlier I was not liking them.

**Comment by dilpreet102** [comment]
If you want then I can make pull request for the above work. And for the night mode effect can you give me time till monday night, but I will try my best  to complete the task done by monday morning.

**Comment by tier3guy** [comment]
Go ahead.

**Comment by narayan954** [comment]
closing this as completed now
