### ISSUE TITLE
Built a custom Scroll Bar

### ISSUE THREAD

**Issue by tier3guy** [tier3guy/Acadmica#9]
Built a custom Scroll Bar maintaining the theme of the org.

**Comment by Aspireve** [comment]
Hey @tier3guy Could I work on this issue?

**Comment by tier3guy** [comment]
Yeah sure @Aspireve. Go for it.

**Comment by Aspireve** [comment]
Yup thanks!!

**Comment by Aspireve** [comment]
Hey I have done it

**Comment by tier3guy** [comment]
Yes, it's great you can commit and push it

**Comment by Aspireve** [comment]
Yup Ill do it soon

**Comment by Aspireve** [comment]
@tier3guy , Should I push it straight to the master branch or make another branch to push it?

**Comment by Aspireve** [comment]
Hey @tier3guy  I guess I need some permission from your side to commit it, could you give me the permission.
![image](https://user-images.githubusercontent.com/93852415/178979593-2af2c0e3-57d9-4a6b-9c7b-56771eae2252.png)

**Comment by Aspireve** [comment]
Yes I finally made the pull request. Do review it.
