### ISSUE TITLE
Documentation in https://acadmica.social/src/pages/interviewPrep/main.html

### ISSUE THREAD

**Issue by tier3guy** [tier3guy/Acadmica#97]
Add content
URL - https://acadmica.social/src/pages/interviewPrep/main.html
![image](https://user-images.githubusercontent.com/73595465/183274575-847c4f08-0a4c-49f0-8006-7c651ada1561.png)

**Comment by Aman-Singh-Kushwaha** [comment]
I can work on this

**Comment by athulmekkoth** [comment]
can I work on this?

**Comment by narayan954** [comment]
@Aman-Singh-Kushwaha sure , go ahead

**Comment by narayan954** [comment]
sorry @athulmekkoth , he claimed this issue earlier.

**Comment by athulmekkoth** [comment]
ok no problem

**Comment by narayan954** [comment]
@Aman-Singh-Kushwaha are you still working on this?

**Comment by Aman-Singh-Kushwaha** [comment]
@narayan954  Yes sir ,
I apologise for late work due personal factors

**Comment by narayan954** [comment]
it's ok , take your time :)

**Comment by akashthedeveloper** [comment]
@narayan954 please assign me this issue would be happy to contribute to it.

**Comment by Aman-Singh-Kushwaha** [comment]
@akashthedeveloper  I am half done on this issue but stucked due to exams, _give me some time_.
I will do it if you really wanna do  something you can work on #68  I will unassign it if you **reply**
