### ISSUE TITLE
Bug in Responsiveness in Tablet view in Home

### ISSUE THREAD

**Issue by Aman-Singh-Kushwaha** [tier3guy/Acadmica#98]
The most **focused** heading _**Acadmica**_ goes inside the photo

![image](https://user-images.githubusercontent.com/96011814/183277904-0233254e-10d2-43ab-86e7-8a67b7601477.png)

**Comment by narayan954** [comment]
would you like to work on this?

**Comment by Aman-Singh-Kushwaha** [comment]
Yes @narayan954

**Comment by narayan954** [comment]
Sure , go ahead!

**Comment by Aman-Singh-Kushwaha** [comment]
I need help with this, Is anyone wants to work on this solo

**Comment by mayank2002-jpg** [comment]
hey! @Aman-Singh-Kushwaha I would like to work on this issue. But want to know the reason why are you leaving this issue. As you already get this one.

**Comment by mayank2002-jpg** [comment]
Hey! @narayan954 can I work on this?

**Comment by narayan954** [comment]
@mayank2002-jpg  yes sure you can!!

**Comment by mayank2002-jpg** [comment]
Thanks! For assigning to me☺

**Comment by Aman-Singh-Kushwaha** [comment]
> hey! @Aman-Singh-Kushwaha I would like to work on this issue. But want to know the reason why are you leaving this issue. As you already get this one.

yes mayank you can work on this, i have also reported for help in the discord group,
May be you have to restructure media queries for tablet mode on page landing section . All the Best👍

**Comment by mayank2002-jpg** [comment]
ok thanks @Aman-Singh-Kushwaha for briefing me about the issue

**Comment by mayank2002-jpg** [comment]
I have completed this and got merged it into the main code. So kindly remove this issue.
